apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  selector:
    matchLabels:
      app: ekart
  replicas: 2
  template:
    metadata:
      labels:
        app: ekart
    spec:
      serviceAccountName: jenkins-sa  # Add this line to specify the Service Account
      containers:
        - name: ekart
          image: hajarnaityahia973/ekart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: ekart-ssvc
spec:
  selector:
    app: ekart
  ports:
    - protocol: "TCP"
      port: 8070
      targetPort: 8070
      nodePort: 31924
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: webapps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: webapps
  name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: webapps
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: webapps
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
